### ISSUE TITLE
License is missing copyright holder

### ISSUE THREAD

**Issue by kimburgess** [voximity/pars3k#3]
Thank you for putting this together. It's a pleasure to use!

I've forked this and will be making some changes that may or may not be compatible with the version you'd like to continue maintaining here. If the modifications are in-line with your wants and desires for this project, more than happy to continue pushing upstream, but will leave that choice up to you.

The [current version of the license](https://github.com/voximity/pars3k/blob/master/LICENSE#L3) is missing your info. So that you are correctly credited, what would you like here? I've set this to your GitHub user on the fork for now, but please do let me know if there's a different entity this should reference.

**Comment by voximity** [comment]
Aha- nice catch! Silly me...

Yes, voximity is fine. Feel free to make any changes in your fork as you see fit. Don't hesitate to open PRs with any changes you'd like to propose.

I haven't worked on this project in quite a while, but the last thing I wanted to do was overhaul the error system. Right now, all parser errors stem back to the `Char` parser, which is not ideal. If you'd like to do something with that, feel free, but it will probably be the next thing I do when I update this project.
